export const ADD_FAVORITO = "ADD_FAVORITO";
export const REMOVE_FAVORITO = "REMOVE_FAVORITO";

export const ADD_LOGIN = "ADD_LOGIN";
export const REMOVE_LOGIN = "REMOVE_LOGIN";

export const ADD_EMPRESA_RECENTE = "ADD_EMPRESA_RECENTE";
export const REMOVE_EMPRESA_RECENTE = "REMOVE_EMPRESA_RECENTE";